### ISSUE TITLE
build instructions don't work

### ISSUE THREAD

**Issue by jheidemann** [gawseed/pyfsdb#4]

**Comment by jheidemann** [comment]
Manual build instructions are:

    git clone git@github.com:gawseed/pyfsdb.git
    cd pyfsdb
    python3 setup.py build
    python3 setup.py install

but the git repo is missing setup.py

**Comment by hardaker** [comment]
Thanks for pointing out that the documentation is obsolete.  Using `setup.py` is no longer recommended by the python community and thus was removed.  I'll fix the instructions.

**Comment by hardaker** [comment]
Instructions fixed to use hatch (there are other tools that will work too).
